Web/WeatherApp/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Sequencing.WeatherApp.Controllers.AppChain;
using Sequencing.WeatherApp.Controllers.OAuth;
using Sequencing.WeatherApp.Controllers.WeatherUnderground;
using Sequencing.WeatherApp.Models;
using Sequencing.WeatherApp.Controllers.DaoLayer;
using Newtonsoft.Json;
using Sequencing.WeatherApp.Controllers;
using log4net;
using Sequencing.WeatherApp.Controllers.PushNotification;

namespace Sequencing.WeatherApp.Controllers
{

    public class DefaultController : ControllerBase
    {
        private readonly AuthWorker authWorker = new AuthWorker(Options.OAuthUrl, Options.OAuthRedirectUrl, Options.OAuthSecret, Options.OAuthAppId);
        public ILog log = LogManager.GetLogger(typeof(DefaultController));
        ISettingService settingService = new UserSettingService();
        public static LocationVerifier.RootObject rootObj;

        /// <summary>
        /// Landing page
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Startup()
        {
            if (Context.IsAuthenticated)
            {
                var _urlReferrer = Request.UrlReferrer;
                if (_urlReferrer == null || _urlReferrer.Host != Request.Url.Host)
                {
                    return RedirectToAction("StartJobSequence");
                }
            }
            return View(new CommonData());
        }

        /// <summary>
        /// Results shortcut - if user has selected dataFile/city then new app chains are started automatically.
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult GoToResults()
        {
            if (!string.IsNullOrEmpty(Context.DataFileId) && !string.IsNullOrEmpty(Context.City))
                return RedirectToAction("StartJob", new { selectedId = Context.DataFileId });
            return RedirectToAction("Startup");
        }


        /// <summary>
        /// OAuth workflow supporting callback action
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult AuthCallback(string code)
        {
            if (code != null)
            {
                var _authInfo = authWorker.GetAuthInfo(code);
                if (_authInfo.Success)
                {
                    var _id = new UserAuthWorker().CreateNewUserToken(_authInfo.Token);
                    var _authTicket = new FormsAuthenticationTicket(1, _id.UserName, DateTime.Now, DateTime.Now.AddDays(15),
                        true, _id.Id.ToString());
                    var encTicket = FormsAuthentication.Encrypt(_authTicket);
                    var faCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);

                    Response.Cookies.Add(faCookie);

                    return RedirectToAction("CheckApp");
                }
                return new ContentResult { Content = "Error while retrieving access token:" + _authInfo.ErrorMessage };
            }
            return new ContentResult { Content = "User cancelled the auth sequence" };
        }

        /// <summary>
        /// About page
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult About()
        {
            return View(new CommonData());
        }

        /// <summary>
        /// Initiates main app sequence
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult StartJobSequence()
        {
            if (!string.IsNullOrEmpty(Context.City) && !string.IsNullOrEmpty(Context.DataFileId))
                return RedirectToAction("CheckApp");
            return RedirectToAction("Location");
        }

        /// <summary>
        /// Location selection
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult Location()
        {
            return View(new CommonData());
        }

        /// <summary>
        /// File selection
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult SelectFile()
        {
            return View("SelectFile", new CommonData());
        }

        /// <summary>
        /// Checks appchains completions. Is used from CheckApp page through AJAX call
        /// </summary>
        /// <param name="jobId"></param>
        /// <param name="jobId2"></param>
        /// <returns></returns>
        [Authorize]
        public bool CheckAppCompletion(string jobId, string jobId2)
        {
            var _srv = new SqApiServiceFacade(Options.ApiUrl);
            var _appStatus = _srv.CheckAppChainStatus(Convert.ToInt64(jobId));
            var _appStatus2 = _srv.CheckAppChainStatus(Convert.ToInt64(jobId2));
            if (_appStatus == "Completed" && _appStatus2 == "Completed")
                return true;
            return false;
        }

        /// <summary>
        /// CheckApp page
        /// </summary>
        /// <param name="jobId"></param>
        /// <param name="jobId2"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult CheckApp()
        {
            return View(new CheckAppData { selectedId = Context.DataFileId });
        }

        /// <summary>
        /// Starts app chains
        /// </summary>
        /// <param name="selectedId"></param>
        /// <returns></returns>
        [Authorize]
        public JsonResult StartJob(string selectedId)
        {
            var _srv = new SqApiServiceFacade(Options.ApiUrl);

            var appChainsParms = new Dictionary<string, string>() { { SqApiServiceFacade.MELANOMA_APP_CHAIN_ID, selectedId }, { SqApiServiceFacade.VITD_APP_CHAIN_ID, selectedId } };
            var appChainsResult = _srv.StartAppChains(appChainsParms);
            return Json(JsonConvert.SerializeObject(new CheckAppData()
            {
                selectedId = Context.DataFileId,
                melanomaRisk = appChainsResult[SqApiServiceFacade.MELANOMA_APP_CHAIN_ID],
                vitD = appChainsResult[SqApiServiceFacade.VITD_APP_CHAIN_ID]
            }), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Original results page, simply redirects to results implementation supplying additional timestamp parameter
        /// </summary>
        /// <param name="jobId"></param>
        /// <param name="jobId2"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult ResultsOriginal(string jobId, string jobId2)
        {
            return RedirectToAction("Results", new { jobId, jobId2, timestamp = DateTime.Now.Ticks });
        }
        public const int MINUTES_FOR_RESULTS_USER_REFRESH = 2;


        /// <summary>
        /// Main results page (dashboard)
        /// </summary>
        /// <param name="jobId"></param>
        /// <param name="jobId2"></param>
        /// <param name="timestamp"></param>
        /// <returns></returns>
        [Authorize]
        public ActionResult Results(string melanomaRisk, string vitD, long? timestamp)
        {
            if (melanomaRisk == null)
                return RedirectToAction("CheckApp");

            var _isAuthenticated = User.Identity.IsAuthenticated;
            var _userName = User.Identity.Name;
            var _runResult = new PersonalizedForecastResultBuilder(_userName, TemperatureMode.F).Build(melanomaRisk, vitD, Context.City);
            Context.City = WeatherWorker.ConvertFromIDToName(Context.City);
            ViewBag.ShowEmail = _isAuthenticated;
            ViewBag.City = Context.City;
            ViewBag.LastJobId = 405762;
            return View(_runResult);
        }

        /// <summary>
        /// Initiates oauth sequence
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult StartAuth()
        {
            return Redirect(authWorker.GetAuthUrl());
        }

        /// <summary>
        /// Logs out user
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Startup");
        }

        public const int MINUTES_FOR_RESULTS_REFRESH = 60;

        /// <summary>
        /// Checks if dashboard page shall be renewed
        /// </summary>
        /// <param name="jobdt"></param>
        /// <returns></returns>
        public bool CheckForJobRefresh(DateTime jobdt)
        {
            if (DateTime.Now.Subtract(jobdt).TotalMinutes > MINUTES_FOR_RESULTS_REFRESH)
                return true;
            return false;
        }


        /// <summary>
        /// Verifies location, routes requests to WU, is used from location page.
        /// </summary>
        /// <param name="city"></param>
        /// <returns></returns>

        [HttpPost]
        public JsonResult FillLocationBox(string city)
        {
            using (var _wb = new WebClient())
            {
                var _res = _wb.DownloadString("http://autocomplete.wunderground.com/aq?format=JSON&query=" + city);
                rootObj = JsonConvert.DeserializeObject<LocationVerifier.RootObject>(_res);
                List<LocationVerifier.RootObject.RESULT> result = new List<LocationVerifier.RootObject.RESULT>();
                foreach (var loc in rootObj.RESULTS)
                    if (loc.type.Equals("city"))
                        result.Add(loc);
                return Json(JsonConvert.SerializeObject(result), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ValidateLocation(string city)
        {
            if (WeatherWorker.WeatherParser(city) != null)
                return Json(JsonConvert.SerializeObject(new { isCorrect = true }), JsonRequestBehavior.AllowGet);

Web/WeatherApp/Views/Default/About.cshtml
@model Sequencing.WeatherApp.Models.CommonData

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<h2>Weather My Way +RTP</h2>
<div class="col-sm-8">
    <p>
        The Weather My Way +RTP app uses Real-Time PersonalizationTM technology to provide you with personalized recommendations that optimize your health.
        This app is personalized by combining the weather forecast with an analysis of your genes. Since your genes are unique, the recommendations you receive are genetically tailored to you.
        This app securely accesses your genetic data that is stored in your Sequencing.com account. Only the genetic data relevant to this app is accessed and no data is stored in your browser or on your mobile device.
        If you don't have genetic data, don't worry! You can still use this app by choosing one of the app's fun sample files. Just click the 'Personalize Me' button on the initial page of the app, connect the app to your Sequencing.com account and you'll then receive access to the sample files.
    </p>

    @Html.ActionLink("Back", "Startup", new object(), new { @class = "btn btn-primary" })
    <a href="https://sequencing.com/user/register" class="btn btn-primary">
        Click here to register for a free account at Sequencing.com
    </a>
</div>

Web/WeatherApp/Views/Default/CheckApp.cshtml
@model Sequencing.WeatherApp.Models.CheckAppData

@{
    ViewBag.Title = "Please wait... this app is now being personalized to you based upon your genes.";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div>
    <script>
        function checkApp() {
            $.ajax({
                url: '@Html.Raw(Url.Action("StartJob", "Default", new { selectedId = Model.selectedId }))',
                contentType: 'application/json',
                method: "GET",
                success: function (data) {
                    var result = JSON.parse(data);
                    if (result.melanomaRisk != null)
                        window.location.replace('/Default/Results/?melanomaRisk=' + result.melanomaRisk + '&vitD=' + result.vitD);
                }
            });
 
        };

        $(function () {
            checkApp();
        });
    </script>
    <div id="preloader">
        <b>Please wait... <br/>This app is now being personalized to you based upon your genes.</b><br/>
    </div>
        <img id="spinner" src="/assets/img/Awesome-cub-pre-loader-Sequencing-com-128px.gif" />

</div>

Web/WeatherApp/Views/Default/Location.cshtml
@using Mandrill.Utilities
@model Sequencing.WeatherApp.Models.CommonData

@{
    ViewBag.Title = "Select location";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<script src="/Scripts/jquery.simpleWeather.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&language=en"></script>
<script src="/assets/js/vidRandom.js"></script>
<script src="/Scripts/autodetect.js"></script>

<div id="titleText">
    <h3 id="titleOne">
        Weather My Way +RTP
    </h3>
    <h4 id="subTitle">Location</h4>
</div>
   @using (Html.BeginForm("", "", new { r = Request.QueryString["r"] }, FormMethod.Post, new { @class = "form-horizontal", @role = "form" }))
   {
    <div id="locInstruction">
        <p>
            Enter your location below<br />
            -OR-<br />
            Click the Auto-detect Button
        </p>
    </div>
    <div id="location">
        <div id="locIn">
            <input type="text" list="cities" id="city" name="city" style="width: 75%" placeholder="Enter your location"/>
            <div id="locButton"><input id="contButton" type="submit" value="Continue"/>
            </div>
            <datalist id="cities"></datalist>
            <script>
                $('#city').on('input', function() {
                    var data = {
                        city: $('#city').val()
                    };
                    $.ajax({
                        url: "/Default/FillLocationBox",
                        type: "POST",
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(data),
                        success: function(data) {
                            var mydata = JSON.parse(data);
                            $('#cities').empty();
                            for (i in mydata) {
                                $('#cities').append("<option value='" + mydata[i]['name'] + "'>");
                            }
                        }
                    });
                    return false;
                });
            </script>
            <br>
            <div class="city-error"><label id="errorlb"></label></div>
            <br>
        </div>
        <div id="discoverButton"><img id="locIcon" src="/assets/img/location-crosshairs-icon-Sequencing-com-32px.png"/><a id="discButton">Auto-detect <br/> location</a>
        </div>
    </div>

   }
<div class="col-sm-offset-2 col-sm-10">


</div>

<style type="text/css">
    #errorlb {
        color: red;
        font-weight: bold;
    }
</style>

<script>
    $('#locButton').click(function (event) {
        event.preventDefault();
        var location = {
            city: $('#city').val()
        };
        var result;
        $.ajax({
            type: "POST",
            url: '@Url.Action("ValidateLocation", "Default")',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(location),
            dataType: "json",
            success: function (dataG) {
                var mydata = JSON.parse(dataG).isCorrect;
                if (mydata) {
                    window.location = '/Default/SaveLocation/?city=' + $('#city').val();                 
                } else {
                    $('#errorlb').text('Invalid city');
                }                    
            }
        });
    })
</script>

<!--<script>
    $(document).ready(function() {
        $("#btnDiscover").click(function(parameters) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var lat = position.coords.latitude;
                var lng = position.coords.longitude;
                codeLatLng(lat, lng);
            }, function(code) {
                $("#city").val("error evaluating location");
            });

        });
    });

    function codeLatLng(lat, lng) {
        var geocoder = new google.maps.Geocoder();
        var latlng = new google.maps.LatLng(lat, lng);
        geocoder.geocode({ 'latLng': latlng }, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                var city = null;
                var country = null;
                var state = null;
                if (results[1]) {
                    //formatted address
                    //find country name
                    for (var i = 0; i < results[0].address_components.length; i++) {
                        for (var b = 0; b < results[0].address_components[i].types.length; b++) {
                            //there are different types that might hold a city admin_area_lvl_1 usually does in come cases looking for sublocality type will be more appropriate
                            if (results[0].address_components[i].types[b] == "locality") {
                                if (!city)
                                    city = results[0].address_components[i];
                            }
                            if (results[0].address_components[i].types[b] == "country") {
                                if (!country)
                                    country = results[0].address_components[i];
                            }
                            if (results[0].address_components[i].types[b] == "administrative_area_level_1") {
                                if (!state)
                                    state = results[0].address_components[i];
                            }
                        }
                    }
                    if (city) {
                        var fin = city.short_name;
                        if (country.short_name == "US")
                            fin += ", " + state.short_name;
                        else
                            fin += ", " + country.short_name;
                        $("#city").val(fin);
                        return;
                    }
                }
            }
            $("#city").val("undetermined");
        });
    }
</script>-->

Web/WeatherApp/Views/Default/Results.cshtml
@using Sequencing.WeatherApp.Models
@model Sequencing.WeatherApp.Models.RunResult

@{
    ViewBag.Title = "Your daily 'Weather +RTP App' recommendations";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<!-- Facebook-->
<div id="fb-root"></div>
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<!--Google+-->
<script src="https://apis.google.com/js/platform.js" async defer></script>

<script type="text/javascript" async defer src="//assets.pinterest.com/js/pinit.js"></script>
    @if (Model.Context.IsAuthenticated)
    {

            <div id="share"><img id="shareButton" src="/assets/img/social-share-icon-64px.png" /></div>

            <div id="shareWindow">
                <h3>Share your genetically tailored forecast</h3>
                <div id="fbShare"><a href="https://www.facebook.com/sharer.php?u=https%3A%2F%2Fweather-app.sequencing.com" target="_blank"><img src="/assets/img/facebook-icon-Simek-sequencing-com.png" height="78" width="78" /></a></div>
                <div id="gPlusOne"><a href="https://plus.google.com/share?url=url=https%3A%2F%2Fweather-app.sequencing.com" target="_blank"><img src="/assets/img/google-plus-icon-Simek-sequencing-com.png" height="78" width="78" /></a></div>

                 <div id="linkedIn"><a href="https://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fweather-app.sequencing.com&title=The%20Weather%20My%20Way%20app%20just%20analyzed%20my%20genes.%20Based%20on%20today%27s%20weather%2C%20My%20recommendation%20is%20&"><img src="/assets/img/linkedin-icon-sequencing-com.png" height="78" width="78" /></a></div>
                <div id="pinterest"><a href="https://www.pinterest.com/pin/create/button/" data-pin-do="buttonBookmark" data-pin-custom="true" data-pin-description="The%20Weather%20My%20Way%20app%20just%20analyzed%20my%20genes.%20Based%20on%20today%27s%20weather%2C%20My%20recommendation%20is%20&"><img src="/assets/img/pinterest-icon-Simek-sequencing-com.png" height="78" width="78" /></a></div>
                
                <div id="twitter"><a href="https://twitter.com/intent/tweet?url=https%3A%2F%2Fweather-app.sequencing.com&text=The%20Weather%20My%20Way%20app%20just%20analyzed%20my%20genes.%20Based%20on%20today%27s%20weather%2C%20My%20recommendation%20is%20" target="_blank"><img src="/assets/img/twitter-icon-Simek-sequencing-com.png" height="78" width="78" /></a></div>
                <div id="reddit"><a href="https://www.reddit.com/submit?url=https%3A%2F%2Fweather-app.sequencing.com&title=The%20Weather%20My%20Way%20app%20just%20analyzed%20my%20genes.%20Based%20on%20today%27s%20weather%2C%20My%20recommendation%20is%20" target="_blank"><img src="/assets/img/reddit-icon-sequencing-com.png" height="78" width="78" /></a></div>
            </div>
    }


<div id="titleText">
    <h3 id="titleOne">
        Weather My Way
    </h3>
    <h4 id="subTitle">with Real-Time Personalization<sup id="tm">TM</sup></h4>
</div>

<div id="now">
    <p id="currentWeather">
        <br /><b>@Model.CurrentWeather.display_location.full</b> <br />
        @Model.CurrentWeather.observation_time

</div>
<div id="tempNow">

    @if (Model.Temperature == TemperatureMode.F)
    {
        <div id="highLow">
            <b>H: @Model.Forecast.forecast.simpleforecast.forecastday[0].high.fahrenheit<sup id="tempSymbolTwo">&#8457</sup></b><br />
            L: @Model.Forecast.forecast.simpleforecast.forecastday[0].low.fahrenheit<sup id="tempSymbolTwo">&#8457</sup>
        </div>
                                <div id="currentTemp">
                                    <b>@Model.CurrentWeather.temp_f</b><sup id="tempSymbol">&#8457</sup>
                                </div>
    }
    else
    {
        <div id="highLow">
            <b>H: @Model.Forecast.forecast.simpleforecast.forecastday[0].high.celsius<sup id="tempSymbolTwo">&#8451</sup></b><br />
            L: @Model.Forecast.forecast.simpleforecast.forecastday[0].low.celsius<sup id="tempSymbolTwo">&#8451</sup>
        </div>
                                <div id="currentTemp">
                                    <b>@Model.CurrentWeather.temp_c</b><sup id="tempSymbol">&#8451</sup>
                                </div>
    }
    <div id="iconNow">
        @{ 
            var timeDay ="day/";

            var night = Model.CurrentWeather.icon_url.Contains("nt_");
            if (night)
            {
                timeDay = "night/";
            }
          
            var source = "/assets/img/WeatherIcons/" + timeDay + Model.Forecast.forecast.simpleforecast.forecastday[0].icon + ".png";

        <img id="forecastIcon" src=@source />}<br /><br /><br /><br />
        <p id="forecastIconText">@Model.Forecast.forecast.simpleforecast.forecastday[0].conditions</p>
    </div>
</div>
<div id="stats">
    <table id="statsTable">
        <tr style="text-align:center">
            <td>wind</td>
            <td>chance of precipitation</td>
            <td>humidity</td>
        </tr>
        <tr style="text-align:center">
            <td>
                @if (Model.Temperature == TemperatureMode.F)
                {
                    @(Model.CurrentWeather.wind_mph + "mph")
                }
                else
                {
                    @(Model.CurrentWeather.wind_kph + "km/h")
                }
                @Model.CurrentWeather.wind_dir
            </td>
            <td>
                @Model.Forecast.forecast.simpleforecast.forecastday[0].pop&#37

            </td>
            <td>
                @Model.CurrentWeather.relative_humidity
            </td>
        </tr>
    </table>
</div>

<div id="tip">
    <h5 id="tipTitle">Your genetically tailored forecast</h5>
    <p id="tipDetail">@Model.Risk</p>
</div>

<div id="forecastDetails">


    @if (Model.Forecast.alerts.Capacity != 0)
    {
        <h5 id="fcDetailTitle" style="color:red">WEATHER ALERT</h5>
                                <p style="color:red">@Model.Forecast.alerts[0].message</p>
    }
    else
    {
        if (Model.Temperature == TemperatureMode.F)
        {
            <h5 id="fcDetailTitle">Today's extended forecast</h5>
                                    @Model.Forecast.forecast.txt_forecast.forecastday[0].fcttext
        }
        else
        {
            <h5 id="fcDetailTitle">Today's extended forecast</h5>
                                    @Model.Forecast.forecast.txt_forecast.forecastday[0].fcttext_metric
        }
    }
</div>




@if (Model.Forecast != null)
{
    <table id="Forecast">
        <tr>
            @for (int _idx = 1; _idx < 5; _idx++)
            {
                <td id="day@_idx">
                    <b>@Model.Forecast.forecast.simpleforecast.forecastday[_idx].date.weekday</b><br />
                    <img class="fcIcon" src=@("/assets/img/WeatherIcons/day/"+Model.Forecast.forecast.simpleforecast.forecastday[_idx].icon+".png") /><br />
                    <p><b> @(Model.Temperature == TemperatureMode.F ? Model.Forecast.forecast.simpleforecast.forecastday[_idx].high.fahrenheit
                                   : Model.Forecast.forecast.simpleforecast.forecastday[_idx].high.celsius)</b><br />
                        @(Model.Temperature == TemperatureMode.F ? Model.Forecast.forecast.simpleforecast.forecastday[_idx].low.fahrenheit
                              : Model.Forecast.forecast.simpleforecast.forecastday[_idx].low.celsius)
                    </p>
                </td>
            }
        </tr>

    </table>
}
<!--<script>
    function checkApp() {

        $.ajax({
            url: '@Html.Raw(Url.Action("CheckForJobRefresh", "Default", new { jobDt = Model.JobDateTime}))',
            contentType: 'application/json',
            method: "GET",
            success: function (data) {
                if (data == "True")
                    window.location.replace('@Html.Raw(Url.Action("GoToResults"))');
            }
        });
        setTimeout(checkApp, 2000);

    };

    $(function () {
        checkApp();
    });
</script>-->

Web/WeatherApp/Views/Default/SelectFile.cshtml
@model Sequencing.WeatherApp.Models.CommonData
@{
    ViewBag.Title = "Select file";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
<script src="/Scripts/jquery-2.1.3.js"></script>
<script src="/Scripts/jquery-ui-1.11.2.min.js"></script>


<div id="titleText">
    <h3 id="titleOne">
        Weather My Way +RTP
    </h3>
    <h4 id="subTitle">Select Your File <img id="question" src="/assets/img/Info-icon-Sequencing-com-16px.png" alt="info" /></h4>
</div>
<div id="fileInstruction">
    <sub><b>RTP = Real-Time Personalization<sup>TM</sup></b></sub>
    <h4><b>RTP is as easy as 1, 2, 3...</b></h4>

    <p>1) Choose whether you want to use a sample file or your own file.</p>
    <ul>
        <li>If you want to use your own file, you will be able to select from a list of files stored in your Sequencing.com account.</li>
    </ul>
    <p>2) Wait a moment for the list of files to appear and then select a file.</p>
    <ul>
        <li>This app's Real-Time Personalization<sup>TM</sup> will then be powered by the genetic data in the file you select.</li>
    </ul>
    3) Press continue.

</div>
<div id="loginbox" class="mainbox">
    <div id="fileSelectBack">
        <div class="panel-body">
            <script type="text/javascript" src="/assets/js/sequencing-file-selector.js?4"></script>
            <script type="text/javascript">
                var Token = "@Model.Context.AuthToken";
                $(document).ready(function() {
                    $('#SelectedId').sequencingFileSelector({
                        accessToken: Token,
                        fileNameElement: $('#SelectedName')
                    });
                });
            </script>
        </div>
        @using (Html.BeginForm("SaveFile", "Default", new { r = Request.QueryString["r"] }))
        {
            <div style="margin-bottom: 5px; margin-top: 10px;" class="form-group">
                <div class="col-sm-12 controls">
                    <input type="hidden" id="SelectedId" name="selectedId" />
                    <input type="hidden" id="SelectedName" name="selectedName" />
                </div>
            </div>
            <button id="continueButton" type="submit">Continue</button>
        }
    </div>
</div>

Web/WeatherApp/Views/Default/Startup.cshtml
@model Sequencing.WeatherApp.Models.CommonData

@{
    ViewBag.Title = "Weather My Way +RTP";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<script src="/Scripts/jquery.simpleWeather.min.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script src="/assets/js/vidRandom.js"></script>




<div id="titleText">
    <h3 id="titleOne">
        Weather My Way
    </h3>
    <h4 id="subTitle">with Real-Time Personalization<sup id="tm">TM</sup></h4>
</div>
<div id="loginContainer">
    <a href="@Url.Action(!Model.Context.IsAuthenticated ? "StartAuth" : "StartJobSequence")" class="btn">
        <img id="login" src="/assets/img/Sign_in_with_Sequencing_com_SSO_button_slate.png" />
    </a><br />
</div>
<div id="regBox">
    <p>
        Don't have a Sequencing.com account?<br />
        <a id="regLink" href="https://sequencing.com/user/register/">Register for a free account</a>
    </p>
</div>

<div id="aboutButton"><b>About</b></div>

<div id="marketButtons">
    <a href="https://geo.itunes.apple.com/us/app/weather-my-way-+rtp/id1116797084?mt=8" class="btn">
        <img id="apple" src="/assets/img/Apple-App-Store-SequencingCom-Genomics-Real-Time-Personalization-RTP.png" height="30" width="100" />
    </a>
    <a href="https://play.google.com/store/apps/details?id=com.sequencing.weather" class="btn">
        <img id="android" src="/assets/img/Android-App-Google-Play-Sequencing-Com-Real-Time-Personalization-RTP.png" height="30" width="100" />
    </a>
</div>

<style>
    #aboutWindow {
        background-color: rgba(210, 210, 210, 0.8);
    }

    img.rsz {
        max-width: 50%;
        max-height: 50%;
    }

    #marketButtons {
        position: absolute;
        width: auto;
        left: 25%;
        top: 52%;
        right: 25%;
        bottom: 42%;
        text-align: center;
    }
</style>